### ISSUE TITLE
command to send text to TO's?

### ISSUE THREAD

**Issue by kspons** [jakerdou/TAMU-ESports-Discord-Bot#4]
I need to request a drop from this week's tournament as I can't be there. I don't believe I can un-register on Smash.gg. I need a TO to drop me from the bracket. Perhaps with "!requestXPool" you can also send the text that follows the command. Or perhaps there should be a "!messageTOs" command (with a timeout per-user, and assurance that it won't be spammed (but let's be real, ppl will probably spam it)).

**Comment by jakerdou** [comment]
> I need to request a drop from this week's tournament as I can't be there. I don't believe I can un-register on Smash.gg. I need a TO to drop me from the bracket. Perhaps with "!requestXPool" you can also send the text that follows the command. Or perhaps there should be a "!messageTOs" command (with a timeout per-user, and assurance that it won't be spammed (but let's be real, ppl will probably spam it)).

That’s a good idea! I’ll work on it later this week

**Comment by jakerdou** [comment]
I added a command, !requestUnregister that lets you notify the TOs that you want to unregister. Hope it helps!
